# Generated by Django 3.2.3 on 2021-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_truck1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck1',
            name='Orderid',
            field=models.IntegerField(),
        ),
    ]
