# Generated by Django 3.2.3 on 2021-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_truck1_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='truck2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderid', models.IntegerField()),
                ('OrderDate', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='truck1',
        ),
    ]
