# Generated by Django 3.2.3 on 2021-07-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210615_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='truck1',
        ),
        migrations.DeleteModel(
            name='truck2',
        ),
    ]
