# Generated by Django 3.2.3 on 2021-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210705_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='truck1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderid', models.IntegerField()),
                ('OrderDate', models.DateField()),
                ('GPs_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='truck2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderid', models.IntegerField()),
                ('OrderDate', models.DateField()),
                ('GPs_link', models.CharField(max_length=30)),
            ],
        ),
    ]
