# Generated by Django 3.2.3 on 2021-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_truck1_truck2'),
    ]

    operations = [
        migrations.CreateModel(
            name='truck3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderid', models.IntegerField()),
                ('OrderDate', models.DateField()),
                ('GPs_link', models.URLField()),
            ],
        ),
    ]
