# Generated by Django 3.2.3 on 2021-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210714_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
